apiVersion: osin.config.openshift.io/v1
auditConfig:
  auditFilePath: ''
  enabled: false
  logFormat: ''
  maximumFileRetentionDays: 0
  maximumFileSizeMegabytes: 0
  maximumRetainedFiles: 0
  policyConfiguration:
  policyFile: ''
  webHookKubeConfig: ''
  webHookMode: ''
corsAllowedOrigins:
kind: OsinServerConfig
kubeClientConfig:
  connectionOverrides:
    acceptContentTypes: ''
    burst: 400
    contentType: ''
    qps: 400
  kubeConfig: "/etc/kubernetes/kubeconfig"
oauthConfig:
  alwaysShowProviderSelection: false
  assetPublicURL: https://console-openshift-console.apps.marktest2.us-east.containers.appdomain.cloud
  grantConfig:
    method: deny
    serviceAccountMethod: prompt
  identityProviders: []
  loginURL: https://api.billsmafia.tylerlovesfloridaalot.com:6443
  masterCA: "/etc/kubernetes/ca.crt"
  masterPublicURL: https://oauth-openshift.apps.marktest2.us-east.containers.appdomain.cloud
  masterURL: https://oauth-openshift.openshift-authentication.svc
  sessionConfig:
    sessionMaxAgeSeconds: 300
    sessionName: ssn
    sessionSecretsFile: "/var/config/system/secrets/v4-0-config-system-session/v4-0-config-system-session"
  templates:
    error: "/var/config/system/secrets/v4-0-config-system-ocp-branding-template/errors.html"
    login: "/var/config/system/secrets/v4-0-config-system-ocp-branding-template/login.html"
    providerSelection: "/var/config/system/secrets/v4-0-config-system-ocp-branding-template/providers.html"
  tokenConfig:
    accessTokenMaxAgeSeconds: 86400
    authorizeTokenMaxAgeSeconds: 300
servingInfo:
  bindAddress: 0.0.0.0:6443
  bindNetwork: tcp4
  certFile: "/var/config/system/secrets/v4-0-config-system-serving-cert/tls.crt"
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
    - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
    - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
    - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
    - TLS_RSA_WITH_AES_128_GCM_SHA256
    - TLS_RSA_WITH_AES_256_GCM_SHA384
    - TLS_RSA_WITH_AES_128_CBC_SHA
    - TLS_RSA_WITH_AES_256_CBC_SHA
  keyFile: "/var/config/system/secrets/v4-0-config-system-serving-cert/tls.key"
  maxRequestsInFlight: 1000
  minTLSVersion: VersionTLS12
  namedCertificates:
    - certFile: "/var/config/system/secrets/v4-0-config-system-router-certs/apps.marktest2.us-east.containers.appdomain.cloud "
      keyFile: "/var/config/system/secrets/v4-0-config-system-router-certs/apps.marktest2.us-east.containers.appdomain.cloud "
      names:
        - "*.apps.marktest2.us-east.containers.appdomain.cloud"
  requestTimeoutSeconds: 300
storageConfig:
  ca: ''
  certFile: ''
  keyFile: ''
  storagePrefix: ''
