kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-apiserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: openshift-oauthserver
  template:
    metadata:
      labels:
        app: openshift-oauthserver
    spec:
      automountServiceAccountToken: false
      containers:
        - name: openshift-oauthserver
          image: ${OPENSHIFT_OAUTHSERVER_IMAGE}
          args:
            - "osinserver"
            - "--config=/etc/kubernetes/config.yaml"
          volumeMounts:
            - mountPath: /etc/kubernetes/
              name: secret
            - mountPath: /var/run/kubernetes
              name: logs
          workingDir: /var/run/kubernetes
      volumes:
        - secret:
            secretName: openshift-oauthserver
          name: secret
        - emptyDir: {}
          name: logs
