apiVersion: v1
kind: Service
metadata:
  name: openshift-oauthserver
spec:
  clusterIP: 172.22.0.20
  selector:
    app: openshift-oauthserver
  ports:
  - name: https
    port: 443
    targetPort: 8443
